name = "comet"
version = "1.0.0"
description = "☄ Leave a gleaming trail of application logs"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bnprtr", repo = "comet" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
