name = "comet"
version = "0.1.0"
description = "Create a gleaming trail of application logs"
licences = ["MIT"]
repository = { type = "github", user = "bnprtr", repo = "comet" }
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
